pipeline {
    agent any

environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
}

parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

stages {
   stage ('Initial cleanup') {
    steps {
      sh 'ls -l'
      sh 'pwd'
      dir("${WORKSPACE}"){
        deleteDir()
      }
      sh 'ls -l'
    }
  }

  stage('Checkout SCM') {
     steps{
	git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/FEREAL12/ansible-config.git'
  }
}

  stage('Prepare Ansible for Execution') {
     steps {
       sh 'echo ${WORKSPACE}'

  }

}
  stage('Run Ansible Playbook'){
	  steps {
      sh 'pwd'
		  ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: '${inventory}', playbook: 'playbooks/site.yml'  
    }
  }

 stage ('Clean Worskpace after build'){
	steps { 
         cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)

   }
  }

 }

}
